// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mov.Core.Api;

namespace Mov.Core.Api.Migrations
{
    [DbContext(typeof(SqliteTranslatorDbContext))]
    partial class SqliteTranslatorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mov.Core.Translators.Models.Schemas.TranslateSchema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EN")
                        .HasColumnType("TEXT");

                    b.Property<string>("JP")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Translates");
                });
#pragma warning restore 612, 618
        }
    }
}
