# Project information
site_name: Mov

# Documentation and theme
docs_dir: 'docs'
theme: 'material'

nav:
  - Index: index.md
  - Assembly: assembly_info.md
  - MainSequence: base_sequence.md
  - Commons:
    - Utility: commons\utility.md
    - Schema: commons\schema.md
    - Accessor: commons\accessor.md
    - Logger: commons\logger.md
    - Repository: commons\repository.md
    - Command: commons\command.md
    - Controller: commons\controller.md
  - Domains:
    - Config: domains\configurator.md
    - Designer: domains\designer.md
    - Analizer: domains\analizer.md
    - Driver: domains\driver.md
    - Game: domains\game.md 
  - 3rdParty: third_party_notice.md

# Extensions
markdown_extensions:
  - admonition
  - toc:
      permalink: '#'
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format